scheduler:
  thread-name-prefix: kafkaProducerThread-
  poolSize: 10
  awaitTerminationSeconds: 10
  daemon: true

#spring:
#  cloud:
#    config:
#      uri: http://localhost:8773
#      fail-fast: false
#      uri: https://github.com/Orisakwe-Nwokocha/Central-Config/

management:
  endpoints:
    web:
      exposure:
        include: refresh

#notification:
#  type: email

spring:
  config:
    import:
      - configserver:http://localhost:8773
      - classpath:userService/config/application.properties
      - classpath:userService/config/application.yml