spring.application.name=kafka-tutorial

orisha.kafka.topic=customer.visit

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=events

#server.port=8086

#spring.config.import=configserver:http://localhost:8773, classpath:userService/config/application.properties
#spring.config.location=classpath:userService/config
#spring.config.additional-location=classpath:userService/config/




#use bootstrap.properties

#spring.cloud.config.uri=http://localhost:8773
#spring.cloud.config.import-check.enabled=false
#spring.cloud.config.enabled=false



#spring.cloud.config.request-read-timeout=5000
#spring.cloud.config.request-connect-timeout=5000
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/gateway
#spring.datasource.username=postgres
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=update
#
#app.secret.key=CKnz84L4KPdQxn3oZk6TlJXg_uul8svfCUG8eWLngtsKwt-guqI_zbKl_d8G9UlqAv6-n9q628tIhWqFLu9wD1DsfQ