#spring.application.name=user-service
#server.port=8083
#
#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=
##spring.jpa.hibernate.ddl-auto=create

spring.config.import=optional:classpath:secrets.properties

#spring.jackson.deserialization.fail-on-unknown-properties=false

#spring.jackson.serialization.indent-output=true

#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/